news.api.key=1ca596677f1c45babd9403548a302261
news.api.country=us
news.api.category=general
news.api.endpoint=https://newsapi.org/v2/top-headlines

thenewsapi.key=i3N4cKdEkJSHqhW9CET8Mz1OSDjiQJB3X0619NKj
thenewsapi.locale=us
thenewsapi.limit=3
thenewsapi.endpoint=https://api.thenewsapi.com/v1/news/top

news.fetch.interval.ms=10800000